// type authorization
export const AUTHORIZATION = 'AUTHORIZATION'
export const AUTHORIZATION_CHANGE_EVENT_INPUT = 'AUTHORIZATION_CHANGE_EVENT_INPUT'
export const ERROR_AUTHORIZATION = 'ERROR_AUTHORIZATION'

// type registration
export const REGISTRATION = 'REGISTRATION'
export const REGISTRATION_CHANGE_EVENT_INPUT = 'REGISTRATION_CHANGE_EVENT_INPUT'
export const ERROR_REGISTRATION_VALIDATION_SERVER = 'ERROR_REGISTRATION_VALIDATION_SERVER'
export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION'

// type authorized
export const AUTHORIZED = 'AUTHORIZED'
export const ADD_TOKENS_IN_STATE = 'ADD_TOKENS_IN_STATE'
export const REFRESH = 'REFRESH'
export const LOGOUT = 'LOGOUT'

// type Articles
export const ARTICLES = 'ARTICLES'
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'

// type ChangeArticle
export const ADD_ARTICLE = 'ADD'
export const ADD_ARTICLE_CHANGE_EVENT_INPUT = 'ARTICLE_CHANGE_EVENT_INPUT'
export const ERROR_VALIDATION_SERVER = 'ERROR_VALIDATION_SERVER'
export const CLEAR_VALIDATION_SERVER = 'CLEAR_VALIDATION_SERVER'
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS'
export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'
export const CHANGE_TYPE_CHANGE_ARTICLE = 'CHANGE_TYPE_CHANGE_ARTICLE'


export const CLEAR_STATE_REDUCERS = 'CLEAR_STATE_REDUCERS'